Budgeting/Controllers/SavingsAccountController.cs
using Budgeting.Models;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Budgeting.Controllers
{
    [Authorize]
    public class SavingsAccountController : BudgetingBaseController
    {
        public SavingsAccountController() : base() { }
        public SavingsAccountController(IApplicationDbContext dbContext) : base(dbContext) { }

        public ActionResult Index()
        {
            var userAccounts = GetAccountsByUser(GetUserId());

            return View(userAccounts);
        }

        public ActionResult Create()
        {
            SavingsAccount account = new SavingsAccount
            {
                ApplicationUserId = GetUserId()
            };
            return View(account);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,ApplicationUserId")] SavingsAccount account)
        {
            if (!ModelState.IsValid) return View(account);

            db.SavingsAccounts.Add(account);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Breakdown(int id)
        {
            var account = db.SavingsAccounts.Find(id);
            if (account == null) return HttpNotFound();

            LoadSavingsFunds(account);
            return View(account);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Breakdown(SavingsAccount account)
        {
            if(!ModelState.IsValid) return View(account);

            db.SetEntityState(account, EntityState.Modified);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var account = db.SavingsAccounts.Find(id);
            if (account == null) return HttpNotFound();

            return View(account);
        }

        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var account = db.SavingsAccounts.Find(id);
            db.SavingsAccounts.Remove(account);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public virtual string GetUserId()
        {
            return User.Identity.GetUserId();
        }

        public virtual List<SavingsAccount> GetAccountsByUser(string userId)
        {
            // maybe wanna pull this out into a service class or something
            var userAccounts = db.SavingsAccounts.Where(s => s.ApplicationUserId == userId).ToList();
            foreach (var account in userAccounts)
            {
                LoadSavingsFunds(account);
            }
            return userAccounts;
        }

        public virtual void LoadSavingsFunds(SavingsAccount account)
        {
            account.Funds = db.SavingsFunds.Where(f => f.AccountID == account.Id).ToList();
        }
    }
}

Budgeting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Budgeter</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Budgeter", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Savings Accounts", "Index", "SavingsAccount")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Budgeter</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>