Budgeting/Models/SavingsAccount.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace Budgeting.Models
{
    public class SavingsAccount
    {
        public int Id { get; set; }

        [Required]
        public string ApplicationUserId { get; set; }
        public virtual ApplicationUser User { get; set; }

        [Required, Column(TypeName = "varchar"), StringLength(25)]
        public string Name { get; set; }

        public ICollection<SavingsFund> Funds { get; set; }

        [Display(Name = "Balance"), DataType(DataType.Currency)]
        public decimal SumOfFunds { get { return Funds.Sum(f => f.Balance); } }

        public SavingsAccount()
        {
            Funds = new List<SavingsFund>();
        }
    }
}

Budgeting/Controllers/SavingsAccountController.cs
using Budgeting.Models;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Budgeting.Controllers
{
    [Authorize]
    public class SavingsAccountController : BudgetingBaseController
    {
        public SavingsAccountController() : base() { }
        public SavingsAccountController(IApplicationDbContext dbContext) : base(dbContext) { }

        public ActionResult Index()
        {
            var userAccounts = GetAccountsByUser(GetUserId());

            return View(userAccounts);
        }

        public ActionResult Create()
        {
            SavingsAccount account = new SavingsAccount
            {
                ApplicationUserId = GetUserId()
            };
            return View(account);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,ApplicationUserId")] SavingsAccount account)
        {
            if (!ModelState.IsValid) return View(account);

            db.SavingsAccounts.Add(account);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Breakdown(int id)
        {
            var account = db.SavingsAccounts.Find(id);
            if (account == null) return HttpNotFound();

            LoadSavingsFunds(account);
            return View(account);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Breakdown(SavingsAccount account)
        {
            if(!ModelState.IsValid) return View(account);

            db.SetEntityState(account, EntityState.Modified);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var account = db.SavingsAccounts.Find(id);
            if (account == null) return HttpNotFound();

            return View(account);
        }

        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var account = db.SavingsAccounts.Find(id);
            db.SavingsAccounts.Remove(account);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public virtual string GetUserId()
        {
            return User.Identity.GetUserId();
        }

        public virtual List<SavingsAccount> GetAccountsByUser(string userId)
        {
            // maybe wanna pull this out into a service class or something
            var userAccounts = db.SavingsAccounts.Where(s => s.ApplicationUserId == userId).ToList();
            foreach (var account in userAccounts)
            {
                LoadSavingsFunds(account);
            }
            return userAccounts;
        }

        public virtual void LoadSavingsFunds(SavingsAccount account)
        {
            account.Funds = db.SavingsFunds.Where(f => f.AccountID == account.Id).ToList();
        }
    }
}

Budgeting/Controllers/SavingsFundController.cs
using System.Data.Entity;
using System.Web.Mvc;
using Budgeting.Models;

namespace Budgeting.Controllers
{
    [Authorize]
    public class SavingsFundController : BudgetingBaseController
    {
        public SavingsFundController() : base() { }

        public SavingsFundController(IApplicationDbContext dbContext) : base(dbContext) { }

        public ActionResult Create(int accountID)
        {
            if (db.SavingsAccounts.Find(accountID) == null) return HttpNotFound();

            var fund = new SavingsFund {AccountID = accountID};
            return View(fund);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Balance,AccountID")] SavingsFund fund)
        {
            if (!ModelState.IsValid) return View(fund);

            db.SavingsFunds.Add(fund);
            db.SaveChanges();
            return RedirectToAction("Breakdown", "SavingsAccount", new {id = fund.AccountID});
        }

        public ActionResult Edit(int id)
        {
            var fund = db.SavingsFunds.Find(id);
            if (fund == null) return HttpNotFound();

            return View(fund);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(SavingsFund fund)
        {
            if (!ModelState.IsValid) return View(fund);

            db.SetEntityState(fund, EntityState.Modified);
            db.SaveChanges();
            return RedirectToAction("Breakdown", "SavingsAccount", new {id = fund.AccountID});
        }

        public ActionResult Delete(int id)
        {
            var fund = db.SavingsFunds.Find(id);
            if (fund == null) return HttpNotFound();

            return View(fund);
        }

        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var fund = db.SavingsFunds.Find(id);
            db.SavingsFunds.Remove(fund);
            db.SaveChanges();
            return RedirectToAction("Breakdown", "SavingsAccount", new {id = fund.AccountID});
        }
    }
}

Budgeting/Controllers/TransactionController.cs
using Budgeting.Models;
using System.Data.Entity;
using System.Web.Mvc;

namespace Budgeting.Controllers
{
    [Authorize]
    public class TransactionController : BudgetingBaseController
    {
        public ActionResult Create(int fundId, Transaction.TransactionType type)
        {
            ViewBag.Fund = db.SavingsFunds.Find(fundId);
            ViewBag.TransactionType = type.ToString();

            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "Id,Amount,FundId,Type")] Transaction transaction)
        {
            if (!ModelState.IsValid) return View();

            transaction.SavingsFund = db.SavingsFunds.Find(transaction.FundId);
            if (transaction.SavingsFund == null) return View();

            transaction.Apply();
            db.SetEntityState(transaction.SavingsFund, EntityState.Modified);
            //db.Transactions.Add(transaction);
            db.SaveChanges();
            return RedirectToAction("Breakdown", "SavingsAccount", new { id = transaction.SavingsFund.AccountID });
        }
    }
}

Budgeting/Views/SavingsAccount/Breakdown.cshtml
@using Budgeting.Models
@model SavingsAccount

@{
    ViewBag.Title = "Account Breakdown";
}

<div style="margin-top: 25px; margin-left: 0; padding-left: 0">
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
</div>

<h2>@Model.Name</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>Account Breakdown</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="row">
                <div class="col-md-1">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-3">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-1">
                    @Html.LabelFor(model => model.SumOfFunds)
                </div>
                <div class="col-md-2">
                    @Html.DisplayFor(model => model.SumOfFunds)
                </div>
            </div>
            @Html.HiddenFor(model => model.ApplicationUserId)

            <h4>Funds</h4>
            <table class="table" style="width:100%">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        Balance
                    </th>
                    <th>
                        Actions
                    </th>
                </tr>

                @foreach (var fund in Model.Funds)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(f => fund.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(f => fund.Balance)
                        </td>
                        <td>
                            <div class="btn-group-vertical">
                                @Html.ActionLink("Deposit", "Create", "Transaction", new {fundId = fund.Id, type = Transaction.TransactionType.Deposit}, new {@class = "btn btn-info"})
                                @Html.ActionLink("Withdraw", "Create", "Transaction", new {fundId = fund.Id, type = Transaction.TransactionType.Withdraw}, new {@class = "btn btn-default"})
                            </div>
                            <div class="btn-group-vertical">
                                @Html.ActionLink("Edit", "Edit", "SavingsFund", new { id = fund.Id }, new { @class = "btn btn-warning" })
                                @Html.ActionLink("Delete", "Delete", "SavingsFund", new { id = fund.Id }, new { @class = "btn btn-danger" })
                            </div>
                        </td>
                    </tr>
                }
            </table>
            @Html.ActionLink("Add New Fund", "Create", "SavingsFund", new { accountID = Model.Id }, new { @class = "btn btn-primary" })
        </div>
        <hr />
        <div class="form-group">
            <div class="col-md-1">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<link href="~/Content/Site.css" rel="stylesheet" />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Budgeting/Views/SavingsAccount/Create.cshtml
@model Budgeting.Models.SavingsAccount

@{
    ViewBag.Title = "Create";
}

<h2>Create New Savings Account</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-10">
            @Html.HiddenFor(model => model.ApplicationUserId, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Budgeting/Views/SavingsAccount/Delete.cshtml
@model Budgeting.Models.SavingsAccount

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this account? Your total balance in this account will be lost.</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

Budgeting/Views/SavingsAccount/Index.cshtml
@model IEnumerable<Budgeting.Models.SavingsAccount>

@{
    ViewBag.Title = "Index";
}

<h2>Savings Accounts</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table" style="width:100%">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SumOfFunds)
        </th>
        <th>
            Actions
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SumOfFunds)
        </td>
        <td>
            @Html.ActionLink("Breakdown", "Breakdown", new { id=item.Id }, new { @class = "btn btn-info" })
            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

<link href="~/Content/Site.css" rel="stylesheet" />